In [4]:
import pandas as pd

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression

In [6]:
# Possui valores de casas na california
housing = datasets.fetch_california_housing()

In [7]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [9]:
# Pega os dados e coloca em um dataframe, pegando os dados que estão em housing.data e as colunas que estão em housing.feature_names
df = pd.DataFrame(housing.data, columns=housing.feature_names)

In [10]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
# Mostra a descrição do dataset
print(housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33:291-297, 1997.

In [12]:
# Pega os dados de target e coloca em um dataframe, pegando os dados que estão em housing.target e a coluna 'MedHouseVal'
dfTarget = pd.DataFrame(housing.target, columns=housing.target_names)

In [14]:
# Mostra o dataframe de target
dfTarget.head()

   MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [16]:
X = df
Y = dfTarget

In [18]:
# Divide os dados em treino e teste, usando a função train_test_split do sklearn, passando os dados de X e Y, o tamanho do teste (20%) e a random_state (42)
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=123)

In [19]:
X_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
9950,4.5694,28.0,6.219512,1.030488,504.0,3.073171,38.38,-122.33
3547,5.6392,18.0,5.951644,1.034816,3010.0,2.911025,34.26,-118.60
4448,1.7292,47.0,3.628032,1.032345,1452.0,3.913747,34.07,-118.21
6984,4.6226,36.0,5.126238,0.985149,988.0,2.445545,33.96,-118.02
4432,2.4375,49.0,4.024390,0.942073,1405.0,4.283537,34.08,-118.20
...,...,...,...,...,...,...,...,...
7763,3.6389,36.0,5.584615,1.115385,490.0,3.769231,33.91,-118.10
15377,4.5391,14.0,6.016688,1.017972,2436.0,3.127086,33.37,-117.24
17730,5.6306,5.0,5.958393,1.031564,2435.0,3.493544,37.33,-121.76
15725,3.8750,44.0,4.739264,1.024540,561.0,1.720859,37.78,-122.44
19966,2.5156,20.0,5.491379,1.117816,1241.0,3.566092,36.21,-119.08

In [20]:
X_test

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
19121,3.7917,40.0,4.959799,1.030151,1039.0,2.610553,38.24,-122.64
20019,4.0217,9.0,5.804577,1.000000,1749.0,3.079225,36.09,-119.05
15104,4.0882,12.0,5.360360,1.070571,3321.0,4.986486,32.85,-116.98
3720,2.2377,27.0,3.376582,1.023207,3403.0,3.589662,34.20,-118.42
8938,4.4211,41.0,5.656904,1.165272,1047.0,2.190377,34.01,-118.47
...,...,...,...,...,...,...,...,...
313,2.7159,45.0,5.306590,1.126074,1132.0,3.243553,37.77,-122.19
4596,1.4413,41.0,2.547009,1.102564,2931.0,4.175214,34.05,-118.28
16287,1.6900,31.0,5.290323,1.154839,576.0,3.716129,37.91,-121.28
5771,2.6729,22.0,4.037433,1.135472,1684.0,3.001783,34.15,-118.27
18254,5.5385,36.0,5.048780,0.956098,475.0,2.317073,37.39,-122.09

In [21]:
y_train

       MedHouseVal
9950         2.875
3547         2.715
4448         1.917
6984         2.197
4432         1.140
...            ...
7763         1.676
15377        1.809
17730        2.862
15725        4.125
19966        0.593

[16512 rows x 1 columns]

In [22]:
y_test

       MedHouseVal
19121        1.516
20019        0.992
15104        1.345
3720         2.317
8938         4.629
...            ...
313          1.014
4596         1.589
16287        0.659
5771         2.171
18254        3.590

[4128 rows x 1 columns]

In [23]:
# Esalona os dados, fazendo com que todas as variáveis númericas tenha a mesma proporção de valores, usando a função StandardScaler do sklearn, passando os dados
scaler = StandardScaler()

In [ ]:
# Escale os dados de treino e teste, usando a função fit_transform do scaler, passando os dados de treino e teste
X_train_Scaled = scaler.fit_transform(X_train)
X_test_Scaled = scaler.fit_transform(X_test)

In [27]:
X_train_Scaled

array([[ 3.67714244e-01, -4.53761462e-02,  3.16164288e-01, ...,
         7.95197399e-04,  1.28942183e+00, -1.38119534e+00],
       [ 9.30744845e-01, -8.40168684e-01,  2.09903463e-01, ...,
        -1.44664485e-02, -6.40792431e-01,  4.83377271e-01],
       [-1.12706938e+00,  1.46472968e+00, -7.11852087e-01, ...,
         7.99128099e-02, -7.29807166e-01,  6.78332584e-01],
       ...,
       [ 9.26218707e-01, -1.87339898e+00,  2.12580734e-01, ...,
         4.03620114e-02,  7.97498292e-01, -1.09626065e+00],
       [ 2.25485873e-03,  1.22629191e+00, -2.71036722e-01, ...,
        -1.26488590e-01,  1.00832267e+00, -1.43618273e+00],
       [-7.13190832e-01, -6.81210176e-01,  2.73206265e-02, ...,
         4.71904727e-02,  2.72779852e-01,  2.43432270e-01]],
      shape=(16512, 8))

In [ ]:
# Modelagem, onde se constroi o modelo de regressão linear, usando a função LinearRegression do sklearn, passando os dados de treino escalonados e os dados de treino de target

# Treina essa IA com o X_train_Scaled e o y_train, usando a função fit do reg, passando os dados de treino escalonados e os dados de treino de target
reg = LinearRegression().fit(X_train_Scaled, y_train)

In [28]:
result = reg.predict(X_test_Scaled)

In [29]:
result

array([[2.36963052],
       [1.42164175],
       [2.03935223],
       ...,
       [0.97891953],
       [1.75012751],
       [3.15660826]], shape=(4128, 1))

In [30]:
# Avaliação do modelo, usando a função score do reg, passando os dados de teste escalonados e os dados de teste de target
reg.score(X_test_Scaled, y_test)

0.6113273240072044